server:
  port: 9200
spring:
  application:
    name: Account-Service
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: manash1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true