server:
  port: 9098
spring:
  application:
    name: Fintech-service
  datasource:
    url: jdbc:mysql://localhost:3306/fintech
    username: root
    password: manash1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false